# Generated by Django 4.2.4 on 2023-08-03 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claim_submission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudDetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fraudulent', models.BooleanField()),
                ('evidence', models.TextField()),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claim_submission.claim')),
            ],
        ),
    ]
